# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-31 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('order_type', models.CharField(max_length=100, null=True)),
                ('order_data', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
