# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dam_Device_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dam_Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('parameter_type', models.IntegerField(null=True)),
                ('parameter_data', models.CharField(max_length=80, null=True)),
                ('dam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('order_type', models.IntegerField(null=True)),
                ('order_data', models.CharField(max_length=80, null=True)),
                ('stationID', models.CharField(default='-1', max_length=80, null=True)),
                ('dam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam')),
            ],
        ),
    ]
