# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-01 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('parameter_type', models.CharField(max_length=100, null=True)),
                ('parameter_data', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
