# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-04 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_management', '0002_parameter_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam_num', models.CharField(max_length=100, null=True)),
                ('order_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('order_type', models.CharField(max_length=100, null=True)),
                ('order_data', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam_num', models.CharField(max_length=100, null=True)),
                ('parameter_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('parameter_type', models.CharField(max_length=100, null=True)),
                ('parameter_data', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Order_1',
        ),
        migrations.DeleteModel(
            name='Parameter_1',
        ),
    ]
