# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order_management', '0003_auto_20180604_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dam_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='dam_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam'),
        ),
    ]
