# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_management', '0004_auto_20180605_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_update_time',
            new_name='update_time',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='parameter_update_time',
            new_name='update_time',
        ),
        migrations.AddField(
            model_name='order',
            name='stationID',
            field=models.CharField(default='-1', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter_data',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter_type',
            field=models.IntegerField(null=True),
        ),
    ]
