# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order_management', '0005_auto_20180605_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dam_num',
            new_name='dam',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='dam_num',
            new_name='dam',
        ),
    ]
