# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-08 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_Device_management', '0007_auto_20180608_1632'),
        ('Order_management', '0008_auto_20180606_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dam_Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('parameter_data', models.IntegerField(null=True)),
                ('dam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam')),
            ],
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='dam',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
