# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-03 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_management', '0009_auto_20180608_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
