# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_num', models.CharField(default='0000000', max_length=80)),
                ('device_num', models.CharField(default='xxxxxxx', max_length=80)),
                ('message_time', models.TimeField(default='12:00', max_length=20)),
                ('working_status', models.CharField(default='off', max_length=20)),
                ('base_num', models.CharField(default='0000000', max_length=80)),
                ('cell_num', models.CharField(default='0000000', max_length=80)),
                ('power', models.CharField(default='0', max_length=20)),
                ('business_model', models.CharField(default='', max_length=80)),
                ('G_Senser_state', models.CharField(default='off', max_length=50)),
                ('location_time', models.TimeField(default='12:00', max_length=20)),
                ('coordinates', models.CharField(default='116.404, 39.915', max_length=60)),
                ('velocity', models.SmallIntegerField(default='0', max_length=20)),
                ('moving_direction', models.CharField(default='', max_length=20)),
                ('height', models.SmallIntegerField(default='0', max_length=20)),
            ],
        ),
    ]
