# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='carrier_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='target',
            name='sex',
            field=models.CharField(default='男', max_length=15),
        ),
        migrations.AlterField(
            model_name='target',
            name='height',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='velocity',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
