# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_monitoring', '0002_auto_20180330_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='carrier_name',
        ),
        migrations.RemoveField(
            model_name='target',
            name='sex',
        ),
    ]
