# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_monitoring', '0003_auto_20180330_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='coordinates',
            field=models.CharField(default='116.404, 39.915', max_length=100),
        ),
    ]
