# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0003_auto_20180403_1536'),
        ('real_time_monitoring', '0004_auto_20180403_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='G_Senser_state',
        ),
        migrations.RemoveField(
            model_name='target',
            name='business_model',
        ),
        migrations.RemoveField(
            model_name='target',
            name='carrier_num',
        ),
        migrations.RemoveField(
            model_name='target',
            name='device_num',
        ),
        migrations.RemoveField(
            model_name='target',
            name='power',
        ),
        migrations.AddField(
            model_name='target',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device_management.Device'),
        ),
        migrations.AddField(
            model_name='target',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='base_num',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='target',
            name='cell_num',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='target',
            name='coordinates',
            field=models.CharField(default='116.404,39.915', max_length=60),
        ),
        migrations.AlterField(
            model_name='target',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='target',
            name='location_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='message_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='moving_direction',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='target',
            name='velocity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='target',
            name='working_status',
            field=models.CharField(max_length=20),
        ),
    ]
