# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_monitoring', '0006_auto_20180408_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device_management.Device'),
        ),
    ]
