# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dam_Device_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WPast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationID', models.CharField(max_length=80, null=True)),
                ('wreal_time', models.DateTimeField(auto_now=True, null=True)),
                ('wreal_type', models.FloatField(null=True)),
                ('Logo', models.FloatField(null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Device')),
            ],
        ),
        migrations.CreateModel(
            name='WReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationID', models.CharField(max_length=80, null=True)),
                ('wreal_time', models.DateTimeField(auto_now=True, null=True)),
                ('wreal_type', models.FloatField(null=True)),
                ('Logo', models.FloatField(null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Device')),
            ],
        ),
    ]
