# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-01 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warning_management', '0002_wpast_d1_d1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WReal_1',
            new_name='WReal_D1',
        ),
    ]
