# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-04 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warning_management', '0003_auto_20180601_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='WPast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam_num', models.CharField(max_length=100, null=True)),
                ('device_num', models.CharField(max_length=100, null=True)),
                ('station', models.CharField(max_length=100, null=True)),
                ('wreal_time', models.DateTimeField(auto_now=True, null=True)),
                ('wreal_type', models.CharField(max_length=100, null=True)),
                ('Logo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam_num', models.CharField(max_length=100, null=True)),
                ('device_num', models.CharField(max_length=100, null=True)),
                ('station', models.CharField(max_length=100, null=True)),
                ('wreal_time', models.DateTimeField(auto_now=True, null=True)),
                ('wreal_type', models.CharField(max_length=100, null=True)),
                ('Logo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WPast_D1_d1',
        ),
        migrations.DeleteModel(
            name='WReal_D1',
        ),
    ]
