# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warning_management', '0005_auto_20180605_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpast',
            name='Logo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wpast',
            name='wreal_type',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wreal',
            name='Logo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='wreal',
            name='wreal_type',
            field=models.FloatField(null=True),
        ),
    ]
