# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warning_management', '0006_auto_20180605_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wpast',
            old_name='station',
            new_name='stationID',
        ),
        migrations.RenameField(
            model_name='wreal',
            old_name='station',
            new_name='stationID',
        ),
    ]
