# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-01 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Displacement_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DReal_D1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_num', models.CharField(max_length=100, null=True)),
                ('station', models.CharField(max_length=100, null=True)),
                ('dreal_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('temperature', models.CharField(max_length=100, null=True)),
                ('voltage', models.CharField(max_length=100, null=True)),
                ('d1', models.CharField(max_length=100, null=True)),
                ('d2', models.CharField(max_length=100, null=True)),
                ('d3', models.CharField(max_length=100, null=True)),
                ('d4', models.CharField(max_length=100, null=True)),
                ('x', models.CharField(max_length=100, null=True)),
                ('y', models.CharField(max_length=100, null=True)),
                ('z', models.CharField(max_length=100, null=True)),
                ('dx', models.CharField(max_length=100, null=True)),
                ('dy', models.CharField(max_length=100, null=True)),
                ('dz', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='DReal_1',
            new_name='DPast_D1_d1',
        ),
    ]
