# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-04 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Displacement_management', '0002_auto_20180601_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam_num', models.CharField(max_length=100, null=True)),
                ('device_num', models.CharField(max_length=100, null=True)),
                ('station', models.CharField(max_length=100, null=True)),
                ('dreal_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('temperature', models.CharField(max_length=100, null=True)),
                ('voltage', models.CharField(max_length=100, null=True)),
                ('d1', models.CharField(max_length=100, null=True)),
                ('d2', models.CharField(max_length=100, null=True)),
                ('d3', models.CharField(max_length=100, null=True)),
                ('d4', models.CharField(max_length=100, null=True)),
                ('x', models.CharField(max_length=100, null=True)),
                ('y', models.CharField(max_length=100, null=True)),
                ('z', models.CharField(max_length=100, null=True)),
                ('dx', models.CharField(max_length=100, null=True)),
                ('dy', models.CharField(max_length=100, null=True)),
                ('dz', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam_num', models.CharField(max_length=100, null=True)),
                ('device_num', models.CharField(max_length=100, null=True)),
                ('station', models.CharField(max_length=100, null=True)),
                ('dreal_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('temperature', models.CharField(max_length=100, null=True)),
                ('voltage', models.CharField(max_length=100, null=True)),
                ('d1', models.CharField(max_length=100, null=True)),
                ('d2', models.CharField(max_length=100, null=True)),
                ('d3', models.CharField(max_length=100, null=True)),
                ('d4', models.CharField(max_length=100, null=True)),
                ('x', models.CharField(max_length=100, null=True)),
                ('y', models.CharField(max_length=100, null=True)),
                ('z', models.CharField(max_length=100, null=True)),
                ('dx', models.CharField(max_length=100, null=True)),
                ('dy', models.CharField(max_length=100, null=True)),
                ('dz', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DPast_D1_d1',
        ),
        migrations.DeleteModel(
            name='DReal_D1',
        ),
        migrations.AddField(
            model_name='dpast',
            name='dam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Displacement_management.DReal'),
        ),
    ]
