# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Displacement_management', '0003_auto_20180604_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpast',
            name='dam',
        ),
        migrations.RemoveField(
            model_name='dpast',
            name='x',
        ),
        migrations.RemoveField(
            model_name='dpast',
            name='y',
        ),
        migrations.RemoveField(
            model_name='dpast',
            name='z',
        ),
        migrations.RemoveField(
            model_name='dreal',
            name='x',
        ),
        migrations.RemoveField(
            model_name='dreal',
            name='y',
        ),
        migrations.RemoveField(
            model_name='dreal',
            name='z',
        ),
        migrations.AddField(
            model_name='dpast',
            name='d',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dpast',
            name='d5',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dpast',
            name='d6',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dpast',
            name='d7',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dpast',
            name='d8',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dreal',
            name='d',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dreal',
            name='d5',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dreal',
            name='d6',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dreal',
            name='d7',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dreal',
            name='d8',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='d1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='d2',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='d3',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='d4',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='dam_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam'),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='device_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Device'),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='dx',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='dy',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='dz',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='station',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='temperature',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='voltage',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='d1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='d2',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='d3',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='d4',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='dam_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam'),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='device_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Device'),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='dx',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='dy',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='dz',
            field=models.CharField(default=0, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='station',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='temperature',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='voltage',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
