# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Displacement_management', '0004_auto_20180605_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dreal',
            old_name='station',
            new_name='stationID',
        ),
        migrations.AddField(
            model_name='dpast',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dpast',
            name='y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dpast',
            name='z',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='d',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='d1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='d2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='d3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='d4',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='d5',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='d6',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='d7',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='d8',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='dx',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='dy',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='dz',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='voltage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='d',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='d1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='d2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='d3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='d4',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='d5',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='d6',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='d7',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='d8',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='dx',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='dy',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='dz',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='voltage',
            field=models.FloatField(null=True),
        ),
    ]
