# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Displacement_management', '0006_auto_20180606_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpast',
            old_name='dam_num',
            new_name='dam',
        ),
        migrations.RenameField(
            model_name='dpast',
            old_name='device_num',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='dreal',
            old_name='dam_num',
            new_name='dam',
        ),
        migrations.RenameField(
            model_name='dreal',
            old_name='device_num',
            new_name='device',
        ),
    ]
