# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Displacement_management', '0008_auto_20180606_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreal',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dreal',
            name='y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dreal',
            name='z',
            field=models.FloatField(null=True),
        ),
    ]
