# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-29 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Displacement_management', '0010_data1_data2_data3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data3',
            new_name='Average_data',
        ),
        migrations.RenameModel(
            old_name='Data2',
            new_name='Processing_data',
        ),
        migrations.RenameModel(
            old_name='Data1',
            new_name='Raw_data',
        ),
    ]
