# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-03 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Displacement_management', '0012_auto_20180703_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='average_data',
            name='stationID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dpast',
            name='stationID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dreal',
            name='stationID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='processing_data',
            name='stationID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='raw_data',
            name='stationID',
            field=models.IntegerField(null=True),
        ),
    ]
