# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-03 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_Device_management', '0007_auto_20180608_1632'),
        ('Displacement_management', '0013_auto_20180703_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='average_data',
            name='dam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam'),
        ),
        migrations.AddField(
            model_name='dpast',
            name='dam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam'),
        ),
        migrations.AddField(
            model_name='dreal',
            name='dam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam'),
        ),
        migrations.AddField(
            model_name='processing_data',
            name='dam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam'),
        ),
        migrations.AddField(
            model_name='raw_data',
            name='dam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam'),
        ),
    ]
