# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-05 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Displacement_management', '0014_auto_20180703_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw_data',
            old_name='d',
            new_name='d1',
        ),
        migrations.AddField(
            model_name='raw_data',
            name='d2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='raw_data',
            name='d3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='raw_data',
            name='d4',
            field=models.FloatField(null=True),
        ),
    ]
