# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_Device_management', '0007_auto_20180608_1632'),
        ('Displacement_management', '0016_convergence_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationID', models.IntegerField(null=True)),
                ('dreal_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('temperature', models.FloatField(null=True)),
                ('voltage', models.FloatField(null=True)),
                ('d1', models.FloatField(null=True)),
                ('d2', models.FloatField(null=True)),
                ('d3', models.FloatField(null=True)),
                ('d4', models.FloatField(null=True)),
                ('d5', models.FloatField(null=True)),
                ('d6', models.FloatField(null=True)),
                ('d7', models.FloatField(null=True)),
                ('d8', models.FloatField(null=True)),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('z', models.FloatField(null=True)),
                ('d', models.FloatField(default=0, null=True)),
                ('dx', models.FloatField(default=0, null=True)),
                ('dy', models.FloatField(default=0, null=True)),
                ('dz', models.FloatField(default=0, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Smooth_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationID', models.IntegerField(null=True)),
                ('station_num', models.CharField(max_length=60, null=True)),
                ('dreal_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('temperature', models.FloatField(null=True)),
                ('voltage', models.FloatField(null=True)),
                ('d', models.FloatField(null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Device')),
            ],
        ),
        migrations.RemoveField(
            model_name='average_data',
            name='dam',
        ),
        migrations.RemoveField(
            model_name='dpast',
            name='dam',
        ),
        migrations.RemoveField(
            model_name='dreal',
            name='dam',
        ),
        migrations.RemoveField(
            model_name='processing_data',
            name='dam',
        ),
        migrations.RemoveField(
            model_name='raw_data',
            name='dam',
        ),
        migrations.AddField(
            model_name='convergence_data',
            name='station_num',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
