# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_management', '0003_auto_20180403_1536'),
        ('device_management', '0002_auto_20180329_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=0)),
                ('last_time', models.DateTimeField(auto_now=True)),
                ('working_status', models.CharField(max_length=60)),
                ('power', models.FloatField(default=0)),
                ('business_model', models.CharField(max_length=80)),
                ('G_Senser_state', models.CharField(max_length=80)),
                ('device_state', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='device_management',
        ),
        migrations.RemoveField(
            model_name='device',
            name='associated_carrier_num',
        ),
        migrations.AddField(
            model_name='device',
            name='associated_carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier_management.Carrier'),
        ),
        migrations.AddField(
            model_name='device',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='card_num',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_num',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='remark',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='storage_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_management.Device'),
        ),
    ]
