# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam_num', models.IntegerField(null=True)),
                ('dam_name', models.CharField(max_length=100, null=True)),
                ('dam_grade', models.CharField(max_length=100, null=True)),
                ('dam_status', models.CharField(max_length=100, null=True)),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_num', models.IntegerField(null=True)),
                ('card_num', models.CharField(max_length=60, null=True)),
                ('power', models.FloatField(default=0)),
                ('x', models.CharField(max_length=60, null=True)),
                ('y', models.CharField(max_length=60, null=True)),
                ('z', models.CharField(max_length=60, null=True)),
                ('remark', models.TextField()),
            ],
        ),
    ]
