# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam_num', models.IntegerField(unique=True)),
                ('dam_name', models.CharField(max_length=100, null=True)),
                ('dam_grade', models.CharField(max_length=100, null=True)),
                ('dam_status', models.CharField(max_length=100, null=True)),
                ('information', models.TextField()),
                ('port_num', models.IntegerField(null=True)),
                ('domain_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_num', models.IntegerField(null=True)),
                ('card_num', models.CharField(max_length=60, null=True)),
                ('power', models.FloatField(default=0)),
                ('at_tip', models.IntegerField(null=True)),
                ('x', models.FloatField(max_length=60, null=True)),
                ('y', models.FloatField(max_length=60, null=True)),
                ('z', models.FloatField(max_length=60, null=True)),
                ('d1', models.FloatField(null=True)),
                ('d2', models.FloatField(null=True)),
                ('d3', models.FloatField(null=True)),
                ('d4', models.FloatField(null=True)),
                ('remark', models.TextField()),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam')),
            ],
        ),
        migrations.CreateModel(
            name='State_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning', models.IntegerField(null=True)),
                ('dreal_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('temperature', models.FloatField(null=True)),
                ('voltage', models.FloatField(null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Stationr_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning', models.IntegerField(null=True)),
                ('dreal_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('temperature', models.FloatField(null=True)),
                ('voltage', models.FloatField(null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Device')),
            ],
        ),
    ]
