# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_Device_management', '0002_auto_20180605_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='power',
            field=models.FloatField(default='-1'),
        ),
    ]
