# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_Device_management', '0003_auto_20180606_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='dam',
            name='domain_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dam',
            name='port_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='power',
            field=models.FloatField(default=0),
        ),
    ]
