# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_Device_management', '0004_auto_20180606_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dam',
            name='dam_num',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
