# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_Device_management', '0005_auto_20180606_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam'),
        ),
        migrations.AlterField(
            model_name='dam',
            name='dam_num',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
