# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-08 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_Device_management', '0006_auto_20180606_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dam',
            name='dam_num',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='dam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Dam'),
        ),
    ]
