# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-11 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_Device_management', '0010_auto_20180810_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='State_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning', models.CharField(max_length=60, null=True)),
                ('dreal_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('temperature', models.FloatField(null=True)),
                ('voltage', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stationr_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning', models.CharField(max_length=60, null=True)),
                ('dreal_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('temperature', models.FloatField(null=True)),
                ('voltage', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='at_tip',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stationr_data',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Device'),
        ),
        migrations.AddField(
            model_name='state_data',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dam_Device_management.Device'),
        ),
    ]
