# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-11 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dam_Device_management', '0011_auto_20180811_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station_data',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='d1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='d2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='d3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='d4',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Station_data',
        ),
    ]
