# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_num', models.CharField(default='0000000', max_length=60, unique=True)),
                ('carrier_name', models.CharField(default='', max_length=100)),
                ('carrier_type', models.CharField(default='学员', max_length=40)),
                ('identity_num', models.CharField(default='0000000', max_length=60)),
                ('sex', models.CharField(default='男', max_length=15)),
                ('birthday', models.DateTimeField(default='2000.01.01', max_length=40)),
                ('nationality', models.CharField(default='', max_length=50)),
                ('work_unit', models.CharField(default='', max_length=80)),
                ('remarks', models.TextField(default='无', max_length=300)),
            ],
        ),
    ]
