# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='birthday',
            field=models.DateField(default='2000.01.01', max_length=40),
        ),
    ]
