# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_management', '0002_auto_20180330_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='carrier_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='carrier_num',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='identity_num',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='remarks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='work_unit',
            field=models.TextField(),
        ),
    ]
