# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_management', '0003_auto_20180403_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='identity_num',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='nationality',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='sex',
            field=models.CharField(default='男', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='work_unit',
            field=models.TextField(null=True),
        ),
    ]
