# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_management', '0004_auto_20180424_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='carrier_type',
            field=models.IntegerField(),
        ),
    ]
