# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_management', '0005_auto_20180425_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='carrier_num',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='identity_num',
            field=models.IntegerField(null=True),
        ),
    ]
