# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-17 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_management', '0006_auto_20180425_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='sex',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
